// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RLS.AwesomeBar.API.Database;

namespace RLS.AwesomeBar.API.Database.Migrations
{
    [DbContext(typeof(BarContext))]
    [Migration("20210430121017_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("RLS.AwesomeBar.API.Database.Category", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Name = "Cocktail",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 394, DateTimeKind.Utc).AddTicks(9218)
                        },
                        new
                        {
                            Name = "Ordinary Drink",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(6419)
                        },
                        new
                        {
                            Name = "Punch / Party Drink",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(6560)
                        },
                        new
                        {
                            Name = "Milk / Float / Shake",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(6727)
                        },
                        new
                        {
                            Name = "Other/Unknown",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(6737)
                        },
                        new
                        {
                            Name = "Cocoa",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(6766)
                        },
                        new
                        {
                            Name = "Shot",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(6781)
                        },
                        new
                        {
                            Name = "Coffee / Tea",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(6885)
                        },
                        new
                        {
                            Name = "Homemade Liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(6910)
                        },
                        new
                        {
                            Name = "Beer",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(6950)
                        },
                        new
                        {
                            Name = "Soft Drink / Soda",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(6993)
                        });
                });

            modelBuilder.Entity("RLS.AwesomeBar.API.Database.Ingredient", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Name = "Light rum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9044)
                        },
                        new
                        {
                            Name = "Lime",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9382)
                        },
                        new
                        {
                            Name = "Sugar",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9395)
                        },
                        new
                        {
                            Name = "Mint",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9404)
                        },
                        new
                        {
                            Name = "Soda water",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9412)
                        },
                        new
                        {
                            Name = "Bourbon",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9458)
                        },
                        new
                        {
                            Name = "Angostura bitters",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9467)
                        },
                        new
                        {
                            Name = "Water",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9509)
                        },
                        new
                        {
                            Name = "Vodka",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9519)
                        },
                        new
                        {
                            Name = "Gin",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9531)
                        },
                        new
                        {
                            Name = "Tequila",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9540)
                        },
                        new
                        {
                            Name = "Lemon",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9548)
                        },
                        new
                        {
                            Name = "Coca-Cola",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9556)
                        },
                        new
                        {
                            Name = "Campari",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9567)
                        },
                        new
                        {
                            Name = "Sweet Vermouth",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9575)
                        },
                        new
                        {
                            Name = "Blended whiskey",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9587)
                        },
                        new
                        {
                            Name = "Powdered sugar",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9597)
                        },
                        new
                        {
                            Name = "Cherry",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9639)
                        },
                        new
                        {
                            Name = "Dry Vermouth",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9652)
                        },
                        new
                        {
                            Name = "Olive",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9661)
                        },
                        new
                        {
                            Name = "Triple sec",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9676)
                        },
                        new
                        {
                            Name = "Lime juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9684)
                        },
                        new
                        {
                            Name = "Salt",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9693)
                        },
                        new
                        {
                            Name = "Ice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9706)
                        },
                        new
                        {
                            Name = "Maraschino cherry",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9714)
                        },
                        new
                        {
                            Name = "Orange peel",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9722)
                        },
                        new
                        {
                            Name = "Ginger ale",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9734)
                        },
                        new
                        {
                            Name = "Apricot brandy",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9743)
                        },
                        new
                        {
                            Name = "Lemon juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9757)
                        },
                        new
                        {
                            Name = "Southern Comfort",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9766)
                        },
                        new
                        {
                            Name = "Amaretto",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9774)
                        },
                        new
                        {
                            Name = "Sloe gin",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9785)
                        },
                        new
                        {
                            Name = "Orange bitters",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9796)
                        },
                        new
                        {
                            Name = "Yellow Chartreuse",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9806)
                        },
                        new
                        {
                            Name = "Lemon peel",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9839)
                        },
                        new
                        {
                            Name = "Creme de Cacao",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9850)
                        },
                        new
                        {
                            Name = "Light cream",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9859)
                        },
                        new
                        {
                            Name = "Nutmeg",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9867)
                        },
                        new
                        {
                            Name = "Brandy",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9877)
                        },
                        new
                        {
                            Name = "Lemon vodka",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9889)
                        },
                        new
                        {
                            Name = "Pineapple juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9899)
                        },
                        new
                        {
                            Name = "Blackberry brandy",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9914)
                        },
                        new
                        {
                            Name = "Kummel",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9925)
                        },
                        new
                        {
                            Name = "Dark rum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9935)
                        },
                        new
                        {
                            Name = "Kahlua",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9944)
                        },
                        new
                        {
                            Name = "Egg white",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9952)
                        },
                        new
                        {
                            Name = "Club soda",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9970)
                        },
                        new
                        {
                            Name = "White Creme de Menthe",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9980)
                        },
                        new
                        {
                            Name = "Tea",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9989)
                        },
                        new
                        {
                            Name = "Whipped cream",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 395, DateTimeKind.Utc).AddTicks(9999)
                        },
                        new
                        {
                            Name = "Apple brandy",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(9)
                        },
                        new
                        {
                            Name = "Applejack",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(19)
                        },
                        new
                        {
                            Name = "Orange",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(32)
                        },
                        new
                        {
                            Name = "Wine",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(41)
                        },
                        new
                        {
                            Name = "Benedictine",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(72)
                        },
                        new
                        {
                            Name = "Champagne",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(83)
                        },
                        new
                        {
                            Name = "Green Creme de Menthe",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(92)
                        },
                        new
                        {
                            Name = "Grand Marnier",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(102)
                        },
                        new
                        {
                            Name = "Bitters",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(114)
                        },
                        new
                        {
                            Name = "Scotch",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(123)
                        },
                        new
                        {
                            Name = "Banana",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(137)
                        },
                        new
                        {
                            Name = "Carbonated water",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(151)
                        },
                        new
                        {
                            Name = "Coffee liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(161)
                        },
                        new
                        {
                            Name = "Tomato juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(180)
                        },
                        new
                        {
                            Name = "Tabasco sauce",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(189)
                        },
                        new
                        {
                            Name = "Celery salt",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(220)
                        },
                        new
                        {
                            Name = "Worcestershire sauce",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(233)
                        },
                        new
                        {
                            Name = "Blue Curacao",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(244)
                        },
                        new
                        {
                            Name = "Lemonade",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(253)
                        },
                        new
                        {
                            Name = "A�ejo rum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(268)
                        },
                        new
                        {
                            Name = "Tia maria",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(277)
                        },
                        new
                        {
                            Name = "Orange juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(287)
                        },
                        new
                        {
                            Name = "Maraschino liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(306)
                        },
                        new
                        {
                            Name = "Grenadine",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(334)
                        },
                        new
                        {
                            Name = "Egg",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(350)
                        },
                        new
                        {
                            Name = "Cachaca",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(366)
                        },
                        new
                        {
                            Name = "Egg yolk",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(386)
                        },
                        new
                        {
                            Name = "Cognac",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(398)
                        },
                        new
                        {
                            Name = "Cherry brandy",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(409)
                        },
                        new
                        {
                            Name = "Port",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(420)
                        },
                        new
                        {
                            Name = "Chocolate ice-cream",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(433)
                        },
                        new
                        {
                            Name = "Dubonnet Rouge",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(455)
                        },
                        new
                        {
                            Name = "Sugar syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(478)
                        },
                        new
                        {
                            Name = "Pineapple",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(555)
                        },
                        new
                        {
                            Name = "Tonic water",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(571)
                        },
                        new
                        {
                            Name = "Orange spiral",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(583)
                        },
                        new
                        {
                            Name = "Strawberries",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(612)
                        },
                        new
                        {
                            Name = "Heavy cream",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(641)
                        },
                        new
                        {
                            Name = "Galliano",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(662)
                        },
                        new
                        {
                            Name = "Irish whiskey",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(684)
                        },
                        new
                        {
                            Name = "Peach brandy",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(693)
                        },
                        new
                        {
                            Name = "Sweet and sour",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(702)
                        },
                        new
                        {
                            Name = "Green Chartreuse",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(720)
                        },
                        new
                        {
                            Name = "Drambuie",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(745)
                        },
                        new
                        {
                            Name = "Orgeat syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(766)
                        },
                        new
                        {
                            Name = "Grapefruit juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(788)
                        },
                        new
                        {
                            Name = "Red wine",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(800)
                        },
                        new
                        {
                            Name = "Raspberry syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(833)
                        },
                        new
                        {
                            Name = "Sherry",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(844)
                        },
                        new
                        {
                            Name = "Coffee brandy",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(854)
                        },
                        new
                        {
                            Name = "Lime vodka",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(885)
                        },
                        new
                        {
                            Name = "Lemon-lime soda",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(903)
                        },
                        new
                        {
                            Name = "Rum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(927)
                        },
                        new
                        {
                            Name = "Milk",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(940)
                        },
                        new
                        {
                            Name = "151 proof rum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(951)
                        },
                        new
                        {
                            Name = "Lime peel",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(961)
                        },
                        new
                        {
                            Name = "Ricard",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(984)
                        },
                        new
                        {
                            Name = "Peychaud bitters",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(994)
                        },
                        new
                        {
                            Name = "Curacao",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1009)
                        },
                        new
                        {
                            Name = "Anisette",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1026)
                        },
                        new
                        {
                            Name = "Cointreau",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1044)
                        },
                        new
                        {
                            Name = "Strawberry schnapps",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1069)
                        },
                        new
                        {
                            Name = "Anis",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1100)
                        },
                        new
                        {
                            Name = "Maple syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1117)
                        },
                        new
                        {
                            Name = "Creme de Cassis",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1127)
                        },
                        new
                        {
                            Name = "Grape juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1146)
                        },
                        new
                        {
                            Name = "Cream",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1188)
                        },
                        new
                        {
                            Name = "Apple juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1199)
                        },
                        new
                        {
                            Name = "Carrot",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1207)
                        },
                        new
                        {
                            Name = "Passion fruit juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1217)
                        },
                        new
                        {
                            Name = "Yoghurt",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1236)
                        },
                        new
                        {
                            Name = "Honey",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1246)
                        },
                        new
                        {
                            Name = "Chocolate syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1258)
                        },
                        new
                        {
                            Name = "Apple",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1273)
                        },
                        new
                        {
                            Name = "Fruit juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1283)
                        },
                        new
                        {
                            Name = "Fruit",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1294)
                        },
                        new
                        {
                            Name = "Mint syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1305)
                        },
                        new
                        {
                            Name = "Cumin seed",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1349)
                        },
                        new
                        {
                            Name = "Asafoetida",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1361)
                        },
                        new
                        {
                            Name = "Mango",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1379)
                        },
                        new
                        {
                            Name = "Ginger",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1392)
                        },
                        new
                        {
                            Name = "Cayenne pepper",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1402)
                        },
                        new
                        {
                            Name = "Aperol",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1416)
                        },
                        new
                        {
                            Name = "Cantaloupe",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1425)
                        },
                        new
                        {
                            Name = "Berries",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1439)
                        },
                        new
                        {
                            Name = "Grapes",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1449)
                        },
                        new
                        {
                            Name = "Kiwi",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1459)
                        },
                        new
                        {
                            Name = "Papaya",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1467)
                        },
                        new
                        {
                            Name = "Cocoa powder",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1521)
                        },
                        new
                        {
                            Name = "Cornstarch",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1530)
                        },
                        new
                        {
                            Name = "Chocolate",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1542)
                        },
                        new
                        {
                            Name = "Cinnamon",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1551)
                        },
                        new
                        {
                            Name = "Vanilla",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1566)
                        },
                        new
                        {
                            Name = "Butter",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1579)
                        },
                        new
                        {
                            Name = "Vanilla extract",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1588)
                        },
                        new
                        {
                            Name = "Half-and-half",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1597)
                        },
                        new
                        {
                            Name = "Marshmallows",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1605)
                        },
                        new
                        {
                            Name = "Espresso",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1624)
                        },
                        new
                        {
                            Name = "Absolut Citron",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1638)
                        },
                        new
                        {
                            Name = "Peach schnapps",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1651)
                        },
                        new
                        {
                            Name = "Cranberry juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1660)
                        },
                        new
                        {
                            Name = "Peach Vodka",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1674)
                        },
                        new
                        {
                            Name = "Sirup of roses",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1684)
                        },
                        new
                        {
                            Name = "Ouzo",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1694)
                        },
                        new
                        {
                            Name = "Baileys irish cream",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1702)
                        },
                        new
                        {
                            Name = "J�germeister",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1713)
                        },
                        new
                        {
                            Name = "Coffee",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1724)
                        },
                        new
                        {
                            Name = "Grain alcohol",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1733)
                        },
                        new
                        {
                            Name = "Spiced rum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1795)
                        },
                        new
                        {
                            Name = "Cardamom",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1819)
                        },
                        new
                        {
                            Name = "Cloves",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1828)
                        },
                        new
                        {
                            Name = "Black pepper",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1837)
                        },
                        new
                        {
                            Name = "Coriander",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1853)
                        },
                        new
                        {
                            Name = "Whipping cream",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1863)
                        },
                        new
                        {
                            Name = "Condensed milk",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1878)
                        },
                        new
                        {
                            Name = "Anise",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1890)
                        },
                        new
                        {
                            Name = "Licorice root",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1898)
                        },
                        new
                        {
                            Name = "Wormwood",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1907)
                        },
                        new
                        {
                            Name = "Apricot",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1917)
                        },
                        new
                        {
                            Name = "Almond flavoring",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1926)
                        },
                        new
                        {
                            Name = "Food coloring",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1936)
                        },
                        new
                        {
                            Name = "Glycerine",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1946)
                        },
                        new
                        {
                            Name = "Angelica root",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1955)
                        },
                        new
                        {
                            Name = "Almond",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1964)
                        },
                        new
                        {
                            Name = "Allspice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1973)
                        },
                        new
                        {
                            Name = "Marjoram leaves",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(1983)
                        },
                        new
                        {
                            Name = "Caramel coloring",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2003)
                        },
                        new
                        {
                            Name = "Cranberries",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2013)
                        },
                        new
                        {
                            Name = "Peppermint extract",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2027)
                        },
                        new
                        {
                            Name = "Coconut syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2061)
                        },
                        new
                        {
                            Name = "Johnnie Walker",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2074)
                        },
                        new
                        {
                            Name = "Fennel seeds",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2084)
                        },
                        new
                        {
                            Name = "Brown sugar",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2095)
                        },
                        new
                        {
                            Name = "Guava juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2106)
                        },
                        new
                        {
                            Name = "Apple cider",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2119)
                        },
                        new
                        {
                            Name = "Rye whiskey",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2133)
                        },
                        new
                        {
                            Name = "Everclear",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2145)
                        },
                        new
                        {
                            Name = "Kool-Aid",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2155)
                        },
                        new
                        {
                            Name = "Carbonated soft drink",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2188)
                        },
                        new
                        {
                            Name = "Sherbet",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2197)
                        },
                        new
                        {
                            Name = "Fresca",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2223)
                        },
                        new
                        {
                            Name = "Peach nectar",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2237)
                        },
                        new
                        {
                            Name = "Firewater",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2268)
                        },
                        new
                        {
                            Name = "Absolut Peppar",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2276)
                        },
                        new
                        {
                            Name = "Cherry liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2288)
                        },
                        new
                        {
                            Name = "Lager",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2303)
                        },
                        new
                        {
                            Name = "Cider",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2312)
                        },
                        new
                        {
                            Name = "Blackcurrant cordial",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2320)
                        },
                        new
                        {
                            Name = "Frangelico",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2353)
                        },
                        new
                        {
                            Name = "Sour mix",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2370)
                        },
                        new
                        {
                            Name = "Whiskey",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2380)
                        },
                        new
                        {
                            Name = "Hot Damn",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2388)
                        },
                        new
                        {
                            Name = "Midori melon liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2402)
                        },
                        new
                        {
                            Name = "Beer",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2413)
                        },
                        new
                        {
                            Name = "Dr. Pepper",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2426)
                        },
                        new
                        {
                            Name = "White rum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2441)
                        },
                        new
                        {
                            Name = "Pisco",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2451)
                        },
                        new
                        {
                            Name = "Irish cream",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2462)
                        },
                        new
                        {
                            Name = "Goldschlager",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2471)
                        },
                        new
                        {
                            Name = "Ale",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2481)
                        },
                        new
                        {
                            Name = "Guinness stout",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2489)
                        },
                        new
                        {
                            Name = "Chocolate liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2499)
                        },
                        new
                        {
                            Name = "Sambuca",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2511)
                        },
                        new
                        {
                            Name = "Erin Cream",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2533)
                        },
                        new
                        {
                            Name = "Advocaat",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2542)
                        },
                        new
                        {
                            Name = "Passion fruit syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2552)
                        },
                        new
                        {
                            Name = "Vanilla ice-cream",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2567)
                        },
                        new
                        {
                            Name = "Oreo cookie",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2575)
                        },
                        new
                        {
                            Name = "Sprite",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2623)
                        },
                        new
                        {
                            Name = "Pink lemonade",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2631)
                        },
                        new
                        {
                            Name = "Iced tea",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2642)
                        },
                        new
                        {
                            Name = "Sarsaparilla",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2660)
                        },
                        new
                        {
                            Name = "7-Up",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2670)
                        },
                        new
                        {
                            Name = "Apple schnapps",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2679)
                        },
                        new
                        {
                            Name = "Peppermint schnapps",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2696)
                        },
                        new
                        {
                            Name = "Jack Daniels",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2712)
                        },
                        new
                        {
                            Name = "Jim Beam",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2726)
                        },
                        new
                        {
                            Name = "Pina colada mix",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2737)
                        },
                        new
                        {
                            Name = "Daiquiri mix",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2746)
                        },
                        new
                        {
                            Name = "Absolut Vodka",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2755)
                        },
                        new
                        {
                            Name = "Butterscotch schnapps",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2775)
                        },
                        new
                        {
                            Name = "Coconut liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2789)
                        },
                        new
                        {
                            Name = "Crown Royal",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2799)
                        },
                        new
                        {
                            Name = "Vermouth",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2820)
                        },
                        new
                        {
                            Name = "Chambord raspberry liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2840)
                        },
                        new
                        {
                            Name = "Godiva liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2883)
                        },
                        new
                        {
                            Name = "Absolut Kurant",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2896)
                        },
                        new
                        {
                            Name = "Pisang Ambon",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2924)
                        },
                        new
                        {
                            Name = "Bitter lemon",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2933)
                        },
                        new
                        {
                            Name = "Cherry Heering",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2952)
                        },
                        new
                        {
                            Name = "Hot chocolate",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2972)
                        },
                        new
                        {
                            Name = "Creme de Banane",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(2984)
                        },
                        new
                        {
                            Name = "Malibu rum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3007)
                        },
                        new
                        {
                            Name = "Dark Creme de Cacao",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3017)
                        },
                        new
                        {
                            Name = "Vanilla vodka",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3032)
                        },
                        new
                        {
                            Name = "Wild Turkey",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3048)
                        },
                        new
                        {
                            Name = "Grape soda",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3058)
                        },
                        new
                        {
                            Name = "Candy",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3068)
                        },
                        new
                        {
                            Name = "Banana liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3085)
                        },
                        new
                        {
                            Name = "Kiwi liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3096)
                        },
                        new
                        {
                            Name = "Peachtree schnapps",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3114)
                        },
                        new
                        {
                            Name = "Surge",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3122)
                        },
                        new
                        {
                            Name = "Jello",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3133)
                        },
                        new
                        {
                            Name = "Fruit punch",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3144)
                        },
                        new
                        {
                            Name = "Cranberry vodka",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3180)
                        },
                        new
                        {
                            Name = "Apfelkorn",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3228)
                        },
                        new
                        {
                            Name = "Schweppes Russchian",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3236)
                        },
                        new
                        {
                            Name = "Corona",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3253)
                        },
                        new
                        {
                            Name = "Bacardi Limon",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3263)
                        },
                        new
                        {
                            Name = "Yukon Jack",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3299)
                        },
                        new
                        {
                            Name = "Coconut rum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3319)
                        },
                        new
                        {
                            Name = "Tropicana",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3331)
                        },
                        new
                        {
                            Name = "Cherries",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3344)
                        },
                        new
                        {
                            Name = "Root beer",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3354)
                        },
                        new
                        {
                            Name = "Aquavit",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3400)
                        },
                        new
                        {
                            Name = "Chocolate milk",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3419)
                        },
                        new
                        {
                            Name = "Kirschwasser",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3433)
                        },
                        new
                        {
                            Name = "Strawberry liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3441)
                        },
                        new
                        {
                            Name = "Black Sambuca",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3458)
                        },
                        new
                        {
                            Name = "Blackcurrant squash",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3469)
                        },
                        new
                        {
                            Name = "Zima",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3479)
                        },
                        new
                        {
                            Name = "Pepsi Cola",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3514)
                        },
                        new
                        {
                            Name = "Orange Curacao",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3531)
                        },
                        new
                        {
                            Name = "Cream of coconut",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3547)
                        },
                        new
                        {
                            Name = "Absinthe",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3564)
                        },
                        new
                        {
                            Name = "Whisky",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3603)
                        },
                        new
                        {
                            Name = "Tennessee whiskey",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3620)
                        },
                        new
                        {
                            Name = "Limeade",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3671)
                        },
                        new
                        {
                            Name = "Melon liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3707)
                        },
                        new
                        {
                            Name = "Mountain Dew",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3716)
                        },
                        new
                        {
                            Name = "Corn syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3739)
                        },
                        new
                        {
                            Name = "Rumple Minze",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3752)
                        },
                        new
                        {
                            Name = "Lime juice cordial",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3765)
                        },
                        new
                        {
                            Name = "Gold tequila",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3776)
                        },
                        new
                        {
                            Name = "Blueberry schnapps",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3794)
                        },
                        new
                        {
                            Name = "Maui",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3810)
                        },
                        new
                        {
                            Name = "Raspberry vodka",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3831)
                        },
                        new
                        {
                            Name = "Triple Sec",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3846)
                        },
                        new
                        {
                            Name = "Cherry Grenadine",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3855)
                        },
                        new
                        {
                            Name = "Lemon Juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3866)
                        },
                        new
                        {
                            Name = "Agave Syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3874)
                        },
                        new
                        {
                            Name = "demerara Sugar",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3910)
                        },
                        new
                        {
                            Name = "lemon juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3924)
                        },
                        new
                        {
                            Name = "maraschino liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3933)
                        },
                        new
                        {
                            Name = "Olive Brine",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3945)
                        },
                        new
                        {
                            Name = "Lime Juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3956)
                        },
                        new
                        {
                            Name = "Pineapple Syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3965)
                        },
                        new
                        {
                            Name = "St. Germain",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3974)
                        },
                        new
                        {
                            Name = "Angostura Bitters",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3982)
                        },
                        new
                        {
                            Name = "Pepper",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3990)
                        },
                        new
                        {
                            Name = "Lavender",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(3999)
                        },
                        new
                        {
                            Name = "gin",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4025)
                        },
                        new
                        {
                            Name = "Peach Bitters",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4034)
                        },
                        new
                        {
                            Name = "Apricot Brandy",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4051)
                        },
                        new
                        {
                            Name = "Orange Juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4060)
                        },
                        new
                        {
                            Name = "Egg Yolk",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4073)
                        },
                        new
                        {
                            Name = "orange juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4102)
                        },
                        new
                        {
                            Name = "Grapefruit Juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4115)
                        },
                        new
                        {
                            Name = "Maraschino Liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4124)
                        },
                        new
                        {
                            Name = "Coconut milk",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4148)
                        },
                        new
                        {
                            Name = "Pineapple Juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4189)
                        },
                        new
                        {
                            Name = "Prosecco",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4199)
                        },
                        new
                        {
                            Name = "Creme de Mure",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4210)
                        },
                        new
                        {
                            Name = "Dark Rum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4220)
                        },
                        new
                        {
                            Name = "Ginger Beer",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4229)
                        },
                        new
                        {
                            Name = "Raspberry Liqueur",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4240)
                        },
                        new
                        {
                            Name = "pineapple juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4249)
                        },
                        new
                        {
                            Name = "Sugar Syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4260)
                        },
                        new
                        {
                            Name = "Soda Water",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4270)
                        },
                        new
                        {
                            Name = "Agave syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4281)
                        },
                        new
                        {
                            Name = "Tomato Juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4292)
                        },
                        new
                        {
                            Name = "Lillet Blanc",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4304)
                        },
                        new
                        {
                            Name = "White Rum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4314)
                        },
                        new
                        {
                            Name = "Vanilla Ice-Cream",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4330)
                        },
                        new
                        {
                            Name = "Whipped Cream",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4343)
                        },
                        new
                        {
                            Name = "caramel sauce",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4351)
                        },
                        new
                        {
                            Name = "chocolate sauce",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4359)
                        },
                        new
                        {
                            Name = "Mini-snickers bars",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4368)
                        },
                        new
                        {
                            Name = "Cranberry Juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4383)
                        },
                        new
                        {
                            Name = "Egg White",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4395)
                        },
                        new
                        {
                            Name = "Fresh Lemon Juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4448)
                        },
                        new
                        {
                            Name = "Fresh Lime Juice",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4465)
                        },
                        new
                        {
                            Name = "lemon",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4478)
                        },
                        new
                        {
                            Name = "Chocolate Sauce",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4490)
                        },
                        new
                        {
                            Name = "Salted Chocolate",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4499)
                        },
                        new
                        {
                            Name = "Maraschino Cherry",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4509)
                        },
                        new
                        {
                            Name = "Blackberries",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4519)
                        },
                        new
                        {
                            Name = "Gold rum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4529)
                        },
                        new
                        {
                            Name = "Pernod",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4539)
                        },
                        new
                        {
                            Name = "Ginger beer",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4552)
                        },
                        new
                        {
                            Name = "Tonic Water",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4595)
                        },
                        new
                        {
                            Name = "Rosemary",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4604)
                        },
                        new
                        {
                            Name = "Mezcal",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4613)
                        },
                        new
                        {
                            Name = "Lillet",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4627)
                        },
                        new
                        {
                            Name = "Orange Peel",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4636)
                        },
                        new
                        {
                            Name = "Orange Bitters",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4647)
                        },
                        new
                        {
                            Name = "Grape Soda",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4665)
                        },
                        new
                        {
                            Name = "Bailey",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4684)
                        },
                        new
                        {
                            Name = "Jagermeister",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4693)
                        },
                        new
                        {
                            Name = "Sweet and Sour",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4706)
                        },
                        new
                        {
                            Name = "Passoa",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4718)
                        },
                        new
                        {
                            Name = "Elderflower cordial",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4730)
                        },
                        new
                        {
                            Name = "Rosso Vermouth",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4738)
                        },
                        new
                        {
                            Name = "Hot Chocolate",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4750)
                        },
                        new
                        {
                            Name = "Irish Whiskey",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4761)
                        },
                        new
                        {
                            Name = "Blended Scotch",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4776)
                        },
                        new
                        {
                            Name = "Honey syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4786)
                        },
                        new
                        {
                            Name = "Ginger Syrup",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4794)
                        },
                        new
                        {
                            Name = "Islay single malt Scotch",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4803)
                        },
                        new
                        {
                            Name = "Falernum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4813)
                        },
                        new
                        {
                            Name = "blackstrap rum",
                            CreatedAt = new DateTime(2021, 4, 30, 12, 10, 17, 396, DateTimeKind.Utc).AddTicks(4844)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
